name: publish

defaults:
  run:
    shell: bash
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
          
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
        
      - name: Run post-install scripts and build
        run: npm rebuild && npm run prepare --if-present

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
